# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c49693c0ac3ee34d87808ddb7a73ab55ae4b4669c31e592bf6627feac370db93fddbbe44a06e01f22302bd7aab158f54a1ba4e7c9d0430a89f1332de197222d8

test:
  secret_key_base: 6901ddad320e26c2e382040e2e884bbaf5a2a67965bda9708f4f3630f6e9faaa0d085d328a201f7c67eb1b0cb942d3724abad878c9aa819cc79dd9e73b4f33b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
