source 'http://rubygems.org'
ruby '2.2.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'
gem 'rack', '~> 1.5.2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
gem 'jquery-turbolinks'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '2.5.3'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem "highcharts-rails"
gem 'simple_calendar', '~> 2.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'
gem "bootstrap-switch-rails"
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # gem 'pry-byebug'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
end

gem 'rails_12factor', group: :production

gem 'rails_log_stdout', github: 'heroku/rails_log_stdout'

gem 'rails3_serve_static_assets', github: 'heroku/rails3_serve_static_assets'

gem 'newrelic_rpm'

gem 'mongoid', '~> 4.0.0'

gem 'sorcery', '~> 0.9.1'

gem 'pretender'

gem 'figaro', github: 'laserlemon/figaro'

gem 'mandrill-api'

gem 'mailgun-ruby', '~>1.0.3', require: 'mailgun'

gem 'wicked_pdf'

gem 'wkhtmltopdf-binary'

gem 'wkhtmltopdf-heroku'

gem 'pusher'

gem 'smarter_csv'

gem 'puma'

gem 'fog-aws', '0.1.1', require: 'fog/aws/storage'

gem 'fog', '1.28', require: 'fog/aws/storage'

gem 'asset_sync'

gem 'sidekiq'

gem 'whenever', :require => false

gem 'gmail', '0.6.0'

gem 'binding_of_caller'

gem 'rails_admin'

gem 'mongoid-paperclip', :require => 'mongoid_paperclip'

gem 'aws-sdk', '~> 1.3.4'

gem 'tinymce-rails', '4.4.3'

gem 'omniauth-google-oauth2'

gem 'google-api-client', '0.8.2'

gem 'launchy'

gem 'oauth2'

gem 'ruby_outlook'

gem 'faraday', '0.9.1'

gem 'twilio-ruby', '4.11.1'

gem 'excon', '~> 0.49.0'

gem 'will_paginate_mongoid', '2.0.1'

gem 'morrisjs-rails', '0.5.1'

gem 'raphael-rails'

gem 'faye-websocket'

gem 'kaminari-mongoid', '0.1.2'

gem 'multi_json', '~> 1.12.0'

gem 'gibbon', '2.2.4'

gem 'ringcentral_sdk', '1.2.3'

gem 'rack-mini-profiler'

gem 'dalli'

gem 'memcachier'
